apiVersion: networking.k8_s.io/v1
kind: Ingress
metadata:
  name: unit-converter-ingress
spec:
  rules:
    - host: unit-converter.local  # The fake domain name we will use
      http:
        paths:
          # Rule 1: Send API requests to the API Server
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: api-server
                port:
                  number: 5000
          # Rule 2: Send everything else to the Frontend
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80